version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: factorio
      POSTGRES_DB: factorio_manager_development
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /factorio_data:/factorio_data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
      - "80:80"
    command: bash -c "bundle install && bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://factorio:password@db/factorio_manager_development
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: development
      FACTORIO_DATA_PATH: /factorio_data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - /factorio_data:/factorio_data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
      - web
    environment:
      DATABASE_URL: postgres://factorio:password@db/factorio_manager_development
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: development
      FACTORIO_DATA_PATH: /factorio_data

volumes:
  postgres_data:
  redis_data:
  factorio_data: